import React,{FormEvent,useEffect,useMemo,useState}from'react'
import{createRoot}from'react-dom/client'
import{CalendarDays,CheckCircle2,Clock3,HeartPulse,LogOut,Search,Stethoscope,UserRound,X}from'lucide-react'
import{api,Appointment,Doctor,setToken,User}from'./api'
import'./styles.css'

const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)}
const niceDate=(v:string)=>new Intl.DateTimeFormat('en',{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v))

function Auth({onAuth}:{onAuth:(u:User)=>void}){
 const[register,setRegister]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);const form=new FormData(e.currentTarget);try{const data=await api<{access_token:string,user:User}>(register?'/auth/register':'/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(form))});setToken(data.access_token);onAuth(data.user)}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 return <main className="auth-page"><section className="auth-copy"><Brand light/><div><p className="eyebrow">Care, without the wait</p><h1>Your health journey,<br/><em>beautifully simple.</em></h1><p>Find the right specialist, choose a convenient time, and manage every appointment in one calm place.</p></div><p>Trusted specialists · Ready when you are</p></section><section className="auth-panel"><div className="auth-card"><div className="mobile-brand"><Brand/></div><p className="eyebrow">Welcome {register?'to ClinicFlow':'back'}</p><h2>{register?'Create your account':'Good to see you'}</h2><p className="muted">{register?'Start booking trusted care in minutes.':'Sign in to manage your care.'}</p>{error&&<div className="alert">{error}</div>}<form onSubmit={submit}>{register&&<label>Full name<input name="name" placeholder="Alex Morgan" required minLength={2}/></label>}<label>Email address<input name="email" type="email" placeholder="you@example.com" required/></label><label>Password<input name="password" type="password" placeholder="At least 8 characters" minLength={8} required/></label><button className="primary" disabled={busy}>{busy?'Please wait…':register?'Create account':'Sign in'} →</button></form><p className="switch">{register?'Already have an account?':'New to ClinicFlow?'} <button onClick={()=>{setRegister(!register);setError('')}}>{register?'Sign in':'Create one'}</button></p><p className="demo">Doctor demo: doctor1@clinic.test / Doctor123!</p></div></section></main>
}

function PatientDashboard({user,onLogout}:{user:User;onLogout:()=>void}){
 const[doctors,setDoctors]=useState<Doctor[]>([]),[appointments,setAppointments]=useState<Appointment[]>([]),[search,setSearch]=useState(''),[selected,setSelected]=useState<Doctor|null>(null),[date,setDate]=useState(tomorrow()),[slots,setSlots]=useState<string[]>([]),[notice,setNotice]=useState(''),[tab,setTab]=useState<'find'|'appointments'>('find')
 const load=()=>Promise.all([api<Doctor[]>('/doctors').then(setDoctors),api<Appointment[]>('/appointments/mine').then(setAppointments)]).catch(e=>setNotice(e.message))
 useEffect(()=>{void load()},[])
 useEffect(()=>{if(selected)api<{starts_at:string}[]>(`/doctors/${selected.id}/slots?date=${date}`).then(s=>setSlots(s.map(x=>x.starts_at))).catch(e=>setNotice(e.message))},[selected,date])
 const filtered=useMemo(()=>doctors.filter(d=>(d.name+' '+d.specialty).toLowerCase().includes(search.toLowerCase())),[doctors,search])
 async function book(slot:string){if(!selected)return;try{await api('/appointments',{method:'POST',body:JSON.stringify({doctor_id:selected.id,slot_time:slot})});setNotice('Appointment confirmed.');setSelected(null);await load();setTab('appointments')}catch(e){setNotice((e as Error).message)}}
 async function cancel(id:number){try{await api(`/appointments/${id}`,{method:'DELETE'});setNotice('Appointment cancelled.');await load()}catch(e){setNotice((e as Error).message)}}
 const booked=appointments.filter(a=>a.status==='booked')
 return <div><Header user={user} onLogout={onLogout}/><div className="mobile-tabs"><button className={tab==='find'?'active':''} onClick={()=>setTab('find')}>Find care</button><button className={tab==='appointments'?'active':''} onClick={()=>setTab('appointments')}>Appointments</button></div><main className="dashboard">{notice&&<div className="toast"><CheckCircle2/>{notice}<button onClick={()=>setNotice('')}><X/></button></div>}<section className={tab==='find'?'':'mobile-hidden'}><p className="eyebrow">Your care, your choice</p><h1>Find your doctor</h1><p className="muted">Browse specialists and book a time that fits your day.</p><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by doctor or specialty…"/></div><div className="doctor-grid">{filtered.map((doctor,i)=><article className="doctor-card" key={doctor.id}><div className={`portrait p${i%3}`}><span>{doctor.name.split(' ').slice(-1)[0][0]}</span><i>Available</i></div><div className="doctor-info"><span className="specialty">{doctor.specialty}</span><h3>{doctor.name}</h3><p><Stethoscope/> Specialist physician</p><button onClick={()=>setSelected(doctor)}>View availability <span>→</span></button></div></article>)}</div></section><aside className={`${tab==='appointments'?'':'mobile-hidden'} appointments-panel`}><p className="eyebrow">Coming up</p><h2>Your appointments</h2>{booked.length===0?<Empty/>:booked.map(a=><article className="appointment" key={a.id}><div className="date-tile"><b>{new Date(a.slot_time).getDate()}</b><span>{new Date(a.slot_time).toLocaleDateString('en',{month:'short'})}</span></div><div><span className="specialty">{a.specialty}</span><h3>{a.doctor_name}</h3><p><Clock3/> {niceDate(a.slot_time)}</p></div><button className="cancel" onClick={()=>cancel(a.id)}>Cancel</button></article>)}</aside></main>{selected&&<div className="modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">Book an appointment</p><h2>{selected.name}</h2><p className="muted">{selected.specialty}</p><label>Choose a date<input type="date" min={tomorrow()} value={date} onChange={e=>setDate(e.target.value)}/></label><h3>Available times</h3><div className="slots">{slots.length?slots.map(s=><button key={s} onClick={()=>book(s)}>{new Date(s).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</button>):<p className="muted">No open slots on this day.</p>}</div></section></div>}</div>
}

function DoctorDashboard({user,onLogout}:{user:User;onLogout:()=>void}){const[items,setItems]=useState<Appointment[]>([]),[date,setDate]=useState(new Date().toISOString().slice(0,10));useEffect(()=>{api<Appointment[]>(`/doctor/schedule?date=${date}`).then(setItems)},[date]);return <div><Header user={user} onLogout={onLogout}/><main className="doctor-dashboard"><p className="eyebrow">Doctor workspace</p><h1>Your schedule</h1><div className="schedule-head"><p className="muted">Review your patient visits for the day.</p><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><section className="schedule-list">{items.length?items.map(a=><article key={a.id}><time>{new Date(a.slot_time).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}</time><span/><div><h3>{a.patient_name}</h3><p>Booked appointment · {user.specialty}</p></div></article>):<Empty/>}</section></main></div>}
function Empty(){return <div className="empty"><div><CalendarDays/></div><h3>No appointments yet</h3><p>Your next visit will appear here.</p></div>}
function Brand({light=false}:{light?:boolean}){return <div className={`brand ${light?'light':''}`}><span><HeartPulse/></span> ClinicFlow</div>}
function Header({user,onLogout}:{user:User;onLogout:()=>void}){return <header><Brand/><nav><span><UserRound/>{user.name}</span><button onClick={onLogout}><LogOut/> Sign out</button></nav></header>}
function App(){const[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(!!localStorage.getItem('token'));useEffect(()=>{if(localStorage.getItem('token'))api<User>('/auth/me').then(setUser).catch(()=>setToken(null)).finally(()=>setLoading(false))},[]);const logout=()=>{setToken(null);setUser(null)};if(loading)return <div className="loading"><HeartPulse/> Loading ClinicFlow…</div>;if(!user)return <Auth onAuth={setUser}/>;return user.role==='doctor'?<DoctorDashboard user={user} onLogout={logout}/>:<PatientDashboard user={user} onLogout={logout}/>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)

